directories = {
# 'fall_23_cohort_23': [],
# 'spring_24_cohort_24': [],
'spring_24_cohort_25': [
    'https://fernando-martinez---about-me-proto---cohort-25.glitch.me/',
    'https://workoptions-.glitch.me/',
    'https://jjimenezabout-me-page.glitch.me/',
    'https://aboutme-derrick.glitch.me/index.html',
    'https://aboutmepage-aaron.glitch.me',
    'https://about-me-justin.glitch.me/',
    'https://star-aboutme.glitch.me/',
    'https://andrews-aboutme.glitch.me/',
    'https://about-me-donovan-reece.glitch.me/',
    'https://faisaj.glitch.me/fj.html',
    'https://diana-guttormsen.glitch.me/',
    'https://aboutmeport.glitch.me/',
    'https://rochean-about-me.glitch.me/',
],
'fall_23_cohort_22': [
    'https://jason-website.glitch.me/',
    'https://victorspage.glitch.me/',
    'https://about-me-project---melissa-arellano.glitch.me/',
    'https://about-me-yalamber.glitch.me/',
    'https://enriqueswebsite.glitch.me/',
    'https://personal-portfolio-nicolascarrillo.glitch.me/',
    'https://personal-portfolio-yeonsu-jung.glitch.me/#about',
    'https://clifford-about-me-project.glitch.me/'
],
'summer_24_cohort_26': [
    'https://ic-about-me-project.glitch.me/',
    'https://profolio-2024.glitch.me/about-me.html',
    'https://about-me-ag.glitch.me/index.html',
    'https://interactive-playlist2300.glitch.me/',
    'https://spicyshrimphome.glitch.me/',
    'https://hassane-elmahi.com/',
    'https://teletraan-files.glitch.me/',
    'https://samia-portfolio-website.glitch.me/#home',
    'https://about-me-anag.glitch.me/',
    'https://song-lyric-page-dm.glitch.me/',
    'https://wildflowersong-6-5.glitch.me/',
    'https://aboutmeprojects.glitch.me/',
    'https://toptradingstrategies.glitch.me/'
],
'fall_24_cohort_27': [
    'https://introduction-project.glitch.me/',
    'https://about-me-jd.glitch.me/',
    'https://about-me-project---rosandi.glitch.me/',
    'https://aiman-lahmamsi.glitch.me/',
    'https://oussama-naji-project.glitch.me/',
    'https://charlien-about-me.glitch.me/',
    'https://simon-huang-about-me.glitch.me/',
    'https://about-olumide.glitch.me/',
    'https://about-me-jiacheng.glitch.me/',
    'https://yutaoli-personal-website.glitch.me/',
    'https://gabevarreola-about-me.glitch.me/',
    'https://austin-hui-porfolio.glitch.me/'
],
'spring_23_cohort_19': [
    'https://boxinggymswebapp.glitch.me/',
    'https://small-owned-restaurants.glitch.me/',
    'https://flavio---final-web-app.glitch.me/index.html',
    'https://big-eats.glitch.me/#',
    'https://sanfranciscoconnect.glitch.me/',
    'https://cuts-by-ron.glitch.me/',
    'https://matthew-wei-about-me.glitch.me/',
    'https://paolas-about-me.glitch.me/',
    'https://j-town.glitch.me/',
    'https://roberto-about-me-page.glitch.me/',
    'https://wz-about-me-.glitch.me/',
    'https://tyler-toan-about-me.glitch.me/',
],
'summer_23_cohort_21': [
    'https://anna-about-me.glitch.me/',
    'https://ashrean.github.io/hw2-ProfessionalPortfolio/',
    'https://about-me-ben93.glitch.me/',
    'https://oceanic-colossal-wire.glitch.me/',
    'https://eliasramirezcarrillo.com/portfolio',
    'https://plume-sprinkle-satellite.glitch.me/',
    'https://brash-ripe-feet.glitch.me/',
    'https://lighthearted-puffpuff-984500.netlify.app/',
],
'summer_23_cohort_20': [
    'https://alvino-page.glitch.me/',
    'https://andy-about-me-page.glitch.me/',
    'https://about-angelo-pasagui.glitch.me/',
    'https://bernard-about-me.glitch.me/',
    'https://clariza-about-me-project.glitch.me/#',
    'https://duanchen.netlify.app/',
    'https://janet-about-me.glitch.me/',
    'https://jessica-aboutme-page.glitch.me/',
    'https://juan-aboutme-page.glitch.me/',
    'https://yu-justin-about-me.glitch.me/',
    'https://draft-finder.glitch.me/',
    'https://about-me-miguel.glitch.me/',
    'https://ng-about-me.glitch.me/',
    'https://vtubers-me-likey-web-app-determined-roomy-sardine.glitch.me/',
    'https://winnieli-aboutme-page.glitch.me/',
],
'fall_2024_cohort_28': [
    'https://sf-parks-ranked-web-app-project.glitch.me/',
    'https://emely-sarceno-bravo-about-me-page.glitch.me/',
    'https://beatrice-aragones.glitch.me/',
    'https://alexa-vega---about-me-page.glitch.me/',
    'https://angelolance-portfolio.glitch.me/',
    'https://omar-dajani-portfolio.glitch.me/pages/',
    'https://aboutmepagep.glitch.me/',
    'https://aboutme-jacoblau.glitch.me/'
],
'spring_25_cohort_29' : [
    'https://portfolio-website-devmission.glitch.me/',
    'https://kenneth-deng-website.glitch.me/#',
    'https://about-me-page-julian.glitch.me/',
    'https://about-me-website-juanlichen.glitch.me/',
    'https://safe-cuboid-slipper.glitch.me/',
    'https://esperanza-aboutme.glitch.me/',
    'https://bright-archive.glitch.me/',
    'https://about-me-project-alex.glitch.me/',
    'https://aboutolliechapman.glitch.me/index.html'
]
        }