directories = {
# 'fall_23_cohort_23': [],
# 'spring_24_cohort_24': [],
'fall_20_cohort_11': ['https://aishasif.glitch.me/',
                'https://aleyda-davalos-personal-page.glitch.me/',
                'https://roomy-canary-class.glitch.me/'
                'https://about-andres-martin.glitch.me/',
                'https://cesarcastro.glitch.me/',
                'https://chuck-lui-web-page.glitch.me/'
                'https://claudia-liu.glitch.me/',
                'https://demerethabout.glitch.me/',
                'https://sedate-scarce-wren.glitch.me/',
                'https://lily-personal-page.glitch.me/',
                'https://about-michelle.glitch.me/',
                'https://rene-ramirez-website.glitch.me/',
                'https://about-me-page-seanwang.glitch.me/',
                'https://mrs-jewel-box.glitch.me/',
                'https://myrealwebsite.glitch.me/',
                'https://aboutzizo.glitch.me/'],
# 'spring_24_cohort_25': [],
# 'fall_23_cohort_22': [],
'fall_24_cohort_28': ['https://sf-parks-ranked-web-app-project.glitch.me/',
                      'https://beatrice-aragones.glitch.me/',
                      'https://alexa-vega---about-me-page.glitch.me/',
                      'https://angelolance-portfolio.glitch.me/',
                      'https://omar-dajani-portfolio.glitch.me/pages/',
                      'https://aboutmepagep.glitch.me/',
                      'https://aboutme-jacoblau.glitch.me/',
                      'https://emely-sarceno-bravo-about-me-page.glitch.me/'],
'spring_22_cohort_16': ['https://destiny-arriaza-about-me.glitch.me/',
        'https://nancycaiwu.glitch.me/',
        'https://ishan-about-me-page.glitch.me/',
        'https://finished-about-me-page.glitch.me/',
        'https://prisca-maduka.glitch.me/',
        'https://about-me-raulperez.glitch.me/',
        'https://about-me-drew-hollenberg.glitch.me/',
        'https://abnerjeronimo-portfolio.glitch.me/',],
# 'summer_24_cohort_26': [],
# 'fall_24_cohort_27': [],
'summer_22_cohort_17': ['https://sunaina-about-me-page.glitch.me/',
                        'https://faheemahshaikhaboutmepage.glitch.me/',
                        'https://sable-outstanding-octopus.glitch.me/',
                        'https://guardadojaime-about-me-page.glitch.me/',
                        'https://luis-flores.glitch.me/',
                        'https://aboutme-pedro.glitch.me/',
                        'https://aboutme-vaidehishah.glitch.me/',
                        'https://about-me-page-stella.glitch.me/',
                        'https://sandys-personal-website.glitch.me/',
                        'https://sandy-v-about-me-page.glitch.me/',
                        'https://veiled-deadpan-cobra.glitch.me/',
                        'https://kelly-about-me-page.glitch.me/',
                        'https://will-i-am-about-me-page.glitch.me/', 
                        'https://aboutmedebora.glitch.me/',
                        'https://nicole-martinez-about-me-2022.glitch.me/',
                        'https://aboutchano.glitch.me/',],
'fall_22_cohort_18': ['https://about-julianne-low.glitch.me/', 
                      'https://priya-vora-portfolio.glitch.me/',
                      'https://marco-dominguez-about-me-pg.glitch.me/#prom',
                      'https://martin-phillip-manuel-about-me.glitch.me/', 
                      'https://bottlenose-metal-rosehip.glitch.me/', 
                      'https://lesther-about-me-page.glitch.me/',
                      'https://apaboutmepageproject.glitch.me/',
                      'https://jades-project.glitch.me/',
                      'https://julian-ortiz-about-me-page.glitch.me',
                      'https://nova-successful-biology.glitch.me/'
                      ], 
# 'spring_23_cohort_19': [],
# 'summer_23_cohort_21': [],
'summer_21_cohort_13': [
        'https://about-me-resume-pj.glitch.me/',
        'https://project-intro-about-me.glitch.me/',
        'https://kr-resume.glitch.me/',
        'https://cord-funky-tenor.glitch.me/',
        'https://curved-checker-august.glitch.me/',
        'https://devmissionresume-stefansuarez.glitch.me/',
        'https://aboutme-resume-wireframe-project-yifei.glitch.me/',
        'https://juans-project.glitch.me/',
        'https://about-me-antonio.glitch.me/',
        'https://web-page-for-about-me-resume-6-30-2021-.glitch.me/',
        'https://my-main-portfolio.glitch.me/',
        'https://ring-humble-suggestion.glitch.me/',
        'https://all-about-mi.glitch.me/',
        'https://succinct-spiral-talon.glitch.me/',],
'summer_21_cohort_14': [
        'https://olivine-attractive-magnesium.glitch.me/',
        'https://bristle-opaque-ton.glitch.me/',
        'https://lu-resume.glitch.me/',
        'https://resume-page112.glitch.me/',
        'https://alex-resume-bootstrap.glitch.me/',
        'https://truthful-stormy-sandalwood.glitch.me/[',
        'https://resume-page-z.glitch.me/',
        'https://personalprofilepage.glitch.me/',
        'https://resume-webproject-gy.glitch.me/',
        'https://jensen-about-me.glitch.me/',
        'https://smooth-internal-walkover.glitch.me/',],
'spring_25_cohort_29': ['https://aboutolliechapman.glitch.me/index.html',
                        'https://about-me-project-alex.glitch.me/',
                        'https://bright-archive.glitch.me/',
                        'https://esperanza-aboutme.glitch.me/',
                        'https://safe-cuboid-slipper.glitch.me/', 
                        'https://about-me-website-juanlichen.glitch.me/',
                        'https://about-me-page-julian.glitch.me/',
                        'https://kenneth-deng-website.glitch.me/#',
                        'https://portfolio-website-devmission.glitch.me/'],
# 'summer_23_cohort_20': [],
'fall_21_cohort_15': [
        'https://landon-about-me.glitch.me/',
        'https://abouttiff.glitch.me/',
        'https://laurag-abm.glitch.me/',
        'https://about-josue.glitch.me/',
        'https://knotty-maze-gargoyleosaurus.glitch.me/',
        'https://about-me-josephine-liang.glitch.me/',
        'https://jiehong-yu.glitch.me/',
        'https://tezhu.glitch.me/',],}