CONFIG_GOODREADS = {
    'PRODUCT': {
            'title': "//*[@id='__next']/div[2]/main/div[1]/div[2]/div[2]/div[1]/div[1]/h1",
            'author' : "//*[@id='__next']/div[2]/main/div[1]/div[2]/div[2]/div[2]/div[1]/h3/div/span[1]/a/span[1]",
            'rating': '//div[@class="RatingStatistics__rating"]',
            'raitings' : '//span[@data-testid="ratingsCount"]',
            'reviews' : '//span[@data-testid="reviewsCount"]',
            'overview' : '//div[@data-testid="description"]//span[@class="Formatted"]',
            'genres': '//div[@data-testid="genresList"]//span[@class="Button__labelItem"]',
            'pages' : '//p[@data-testid="pagesFormat"]',
            'publish_date' : '//p[@data-testid="publicationInfo"]',
    },
    'NEXT_PAGE_BUTTON_XPATH': '//a[@class="next_page" and @rel="next"]',
    'PRODUCTS':  '//*[@id="bodycontainer"]/div[3]/div[1]/div[2]/div[2]/table/tbody/tr/td[2]/a',
    'MULTIPLE': {'genres' : 0},
    'URLS' : ['https://www.goodreads.com/search?utf8=%E2%9C%93&query=Art',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Biography',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Classics',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Comics',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Cookbooks',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Fantasy',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Fiction',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Graphic+Novels',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Historical+Fiction',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=History',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Horror',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Memoir',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Music',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Mystery',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Nonfiction',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Poetry',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Romance',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Science',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Science+Fiction',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Sports',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Thriller',
              'https://www.goodreads.com/search?utf8=%E2%9C%93&query=Young+Adult'
              ],
    'DRIVER_PATH': './drivers/geckodriver',
    'HEADLESS': True,
    'CATEGORIES_BUTTON' : '//span[text()="Browse ▾"]',
    'CATEGORIES' : '//ul[contains(@class, "genreList")]//li/a',
    'POPUP': '//div[contains(@class, "modal__content")]',
    'POPUP_BUTTON': '//button[@class="gr-iconButton"][.//img[@alt="Dismiss"]]'
}


CONFIG_STOCKX = {
    'PRODUCT': {
        'name': '//h1[@data-component="primary-product-title"]',
        'img': '//div[@id="three-sixty-image"]//img[@data-image-type="360"]', 
        'retail_price': '//div[@class="RatingStatistics__rating"]',
        'release_data' : '//div[@data-component="product-trait"][.//span[text()="Release Date"]]//p',
        'description' : '//div[@data-component="ProductDescription" and @data-testid="product-description"]/p',
        'style' : '//div[@data-component="product-trait"][.//span[text()="Style"]]/p',
        'price_range_year' : '//div[contains(@class, "chakra-stat")]//dt[span[text()="Price Range"] and span[@class="chakra-text css-1oadxzv" and text()="Last 12 Months"]]/following-sibling::dd'
    },
    'NEXT_PAGE_BUTTON_XPATH': '//a[@aria-label="Next"]',
    'PRODUCTS':  '//a[@data-testid="productTile-ProductSwitcherLink"]/@href',
    'MULTIPLE': None,
    'URLS' : ['https://stockx.com/search?s==adidas&category=sneakers',
              'https://stockx.com/search?s==Air+Jordan&category=sneakers',
              'https://stockx.com/search?s==ASICS&category=sneakers',
              'https://stockx.com/search?s==New Balance&category=sneakers',
              'https://stockx.com/search?s==Nike&category=sneakers',
              'https://stockx.com/search?s==Louis+Vuitton&category=sneakers',
              'https://stockx.com/search?s==Yeezy&category=converse'
              ],
    'DRIVER_PATH': './drivers/geckodriver',
    'HEADLESS': True,
    'CATEGORIES_BUTTON' : '',
    'CATEGORIES' : ''
}
