"""string to text for overview

Revision ID: 4686ac018d23
Revises: ea7e9ea51352
Create Date: 2025-08-06 14:44:24.868687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4686ac018d23"
down_revision: Union[str, Sequence[str], None] = "ea7e9ea51352"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column("author", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column("rating", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column(
            "raitings", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
        sa.Column("reviews", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column("overview", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("genres", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column("pages", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column(
            "publish_date", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("books_pkey")),
    )
    # ### end Alembic commands ###
