"""fixed ratings typo

Revision ID: 4788d1316e37
Revises: 2d61480a3998
Create Date: 2025-08-20 14:12:51.160496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4788d1316e37"
down_revision: Union[str, Sequence[str], None] = "2d61480a3998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "raitings", new_column_name="ratings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "ratings", new_column_name="raitings")

    # ### end Alembic commands ###
