"""all to text

Revision ID: 7a8773495d80
Revises: 4686ac018d23
Create Date: 2025-08-06 14:46:32.411163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a8773495d80"
down_revision: Union[str, Sequence[str], None] = "4686ac018d23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("author", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("rating", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("raitings", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reviews", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("overview", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("genres", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("pages", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publish_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("books_pkey")),
    )
    # ### end Alembic commands ###
