"""string to text for overview

Revision ID: ea7e9ea51352
Revises: b5545e4317d2
Create Date: 2025-08-06 14:40:52.943228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7e9ea51352'
down_revision: Union[str, Sequence[str], None] = 'b5545e4317d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('raitings', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('reviews', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('overview', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('genres', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pages', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('publish_date', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('books_pkey'))
    )
    # ### end Alembic commands ###
